export const PREORDER = 'PREORDER'
export const PLANO = 'PLANO'
export const TIQUE_TAQUES = 'TIQUE-TAQUES'
export const FUNCIONARIOS = 'FUNCIONARIOS'
export const DADOS = 'DADOS'
export const ENDERECO = 'ENDERECO'